# Generated by Django 3.0.3 on 2020-06-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('L', 'Likert'), ('O', 'Open ended'), ('M', 'Multiple choice')], default='L', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Likert',
        ),
        migrations.CreateModel(
            name='Likert',
            fields=[
            ],
            options={
                'verbose_name': 'Likert question',
                'verbose_name_plural': 'Likert questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.question',),
        ),
    ]
