# Generated by Django 3.0.3 on 2020-06-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_auto_20200609_2250"),
    ]

    operations = [
        migrations.RemoveField(model_name="mcquestionattempt", name="answer",),
        migrations.RemoveField(model_name="mcquestionattempt", name="question",),
        migrations.RemoveField(
            model_name="mcquestionattempt", name="questionattempt_ptr",
        ),
        migrations.RemoveField(model_name="openendedattempt", name="question",),
        migrations.RemoveField(
            model_name="openendedattempt", name="questionattempt_ptr",
        ),
        migrations.DeleteModel(name="LikertAttempt",),
        migrations.DeleteModel(name="MCQuestionAttempt",),
        migrations.DeleteModel(name="OpenEndedAttempt",),
        migrations.CreateModel(
            name="LikertAttempt",
            fields=[],
            options={
                "verbose_name": "Likert attempt",
                "verbose_name_plural": "Likert attempts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quiz.questionattempt",),
        ),
        migrations.CreateModel(
            name="MCQuestionAttempt",
            fields=[],
            options={
                "verbose_name": "Multiple choice questions attempt",
                "verbose_name_plural": "Multiple choice questions attempts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quiz.questionattempt",),
        ),
        migrations.CreateModel(
            name="OpenEndedAttempt",
            fields=[],
            options={
                "verbose_name": "Open ended attempt",
                "verbose_name_plural": "Open ended attempts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("quiz.questionattempt",),
        ),
        migrations.AddField(
            model_name="questionattempt",
            name="answer_content",
            field=models.TextField(
                blank=True, null=True, verbose_name="student answer"
            ),
        ),
        migrations.AddField(
            model_name="questionattempt",
            name="correct",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="questionattempt",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="quiz.Question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionattempt",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("H", "Header"),
                    ("L", "Likert"),
                    ("O", "Open ended"),
                    ("M", "Multiple choice"),
                ],
                default="L",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
