# Generated by Django 3.0.7 on 2020-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_questionattempt_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='multiplechoice_answer',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='multiplechoice_answer',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.MCAnswer'),
        ),
    ]
