# Generated by Django 3.0.7 on 2020-06-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200613_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionattempt',
            old_name='multiplechoice_answer',
            new_name='multiplechoice_answers',
        ),
    ]
