# Generated by Django 3.0.7 on 2020-06-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20200615_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='Enter the content that you want displayed.', max_length=1000, verbose_name='content'),
        ),
    ]
