# Generated by Django 3.0.7 on 2020-06-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200615_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likert',
            options={'verbose_name': 'likert question', 'verbose_name_plural': 'likert questions'},
        ),
        migrations.AlterModelOptions(
            name='likertanswer',
            options={'verbose_name': 'likert answer (scale definition)', 'verbose_name_plural': 'likert answers (scale definition)'},
        ),
        migrations.AlterField(
            model_name='likertanswer',
            name='legend',
            field=models.TextField(blank=True, help_text='Legend for the likert scale values.', verbose_name='legend'),
        ),
        migrations.AlterField(
            model_name='likertanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Likert', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='likertanswer',
            name='scale_max',
            field=models.PositiveIntegerField(default=5, verbose_name='scale max'),
        ),
        migrations.AlterField(
            model_name='likertanswer',
            name='scale_min',
            field=models.PositiveIntegerField(default=1, verbose_name='scale min'),
        ),
    ]
