# Generated by Django 3.0.7 on 2020-06-15 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200610_1732'),
        ('courses', '0013_auto_20200615_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0020_auto_20200615_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertattempt',
            options={'verbose_name': 'likert attempt', 'verbose_name_plural': 'likert attempts'},
        ),
        migrations.AlterModelOptions(
            name='mcquestionattempt',
            options={'verbose_name': 'multiple choice questions attempt', 'verbose_name_plural': 'multiple choice questions attempts'},
        ),
        migrations.AlterModelOptions(
            name='openendedattempt',
            options={'verbose_name': 'open ended attempt', 'verbose_name_plural': 'open ended attempts'},
        ),
        migrations.AlterModelOptions(
            name='questionattempt',
            options={'verbose_name': 'question attempt', 'verbose_name_plural': 'question attempts'},
        ),
        migrations.AlterModelOptions(
            name='questiongroupheader',
            options={'verbose_name': 'question group header', 'verbose_name_plural': 'question group headers'},
        ),
        migrations.AlterModelOptions(
            name='quizscore',
            options={'verbose_name': 'quiz score', 'verbose_name_plural': 'quiz scores'},
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=0, verbose_name='attempt number'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='correct',
            field=models.NullBooleanField(verbose_name='correct'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='multiplechoice_answers',
            field=models.ManyToManyField(blank=True, to='quiz.MCAnswer', verbose_name='multiple choice answers'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='question_type',
            field=models.CharField(choices=[('H', 'Header'), ('L', 'Likert'), ('O', 'Open ended'), ('M', 'Multiple choice')], max_length=1, verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz', verbose_name='quiz'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='videos.VideoFile', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz', verbose_name='quiz'),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
    ]
