# Generated by Django 3.0.7 on 2020-06-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20200615_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcanswer',
            name='content_en',
            field=models.CharField(help_text='Enter the answer text that you want displayed', max_length=1000, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='mcanswer',
            name='content_fr',
            field=models.CharField(help_text='Enter the answer text that you want displayed', max_length=1000, null=True, verbose_name='content'),
        ),
    ]
