# Generated by Django 3.0.7 on 2020-06-22 22:04

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20200615_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='likertanswer',
            name='answer_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default=[2, 3], help_text='Set the minimum and maximum acceptable values.', verbose_name='answer range values'),
        ),
        migrations.AddField(
            model_name='likertanswer',
            name='check_answer',
            field=models.BooleanField(default=False, help_text='Check the answer value?', verbose_name='check answer'),
        ),
    ]
