# Generated by Django 3.0.7 on 2020-06-22 22:06

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20200622_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='likertanswer',
            name='scale_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=[1, 5], help_text='Set the likert scale values.', verbose_name='scale range values'),
        ),
    ]
