# Generated by Django 3.0.7 on 2020-06-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_likertanswer_scale_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertanswer',
            name='scale_max',
        ),
        migrations.RemoveField(
            model_name='likertanswer',
            name='scale_min',
        ),
    ]
