# Generated by Django 3.0.7 on 2020-06-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20200624_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcanswer',
            old_name='correct',
            new_name='check',
        ),
    ]
