# Generated by Django 3.0.7 on 2020-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20200624_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcanswer',
            name='check',
            field=models.BooleanField(default=False, help_text='Should this answer be checked/marked?', verbose_name='check'),
        ),
    ]
