# Generated by Django 3.0.7 on 2020-07-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20200719_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='require_answers',
            field=models.BooleanField(default=False, verbose_name='require participant to answer all questions'),
        ),
    ]
