# Generated by Django 3.0.7 on 2020-09-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_quiz_assessment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assessment_max_mistakes',
            field=models.PositiveIntegerField(default=0, help_text='If the participant exceeds this value, the quiz is marked as failed', verbose_name='maximum number of mistakes'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='assessment_min_percentage',
            field=models.PositiveIntegerField(default=80, help_text='If the participant score percentage is below this value, the quiz is marked as failed', verbose_name='minimum percentage acceptable'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='assessment_method',
            field=models.CharField(choices=[('NO', 'None'), ('MP', 'Minimum Percentage'), ('MN', 'Maximum Number of Mistakes')], default='NO', help_text='method for assessing if the quiz has been', max_length=2, verbose_name='assessment method'),
        ),
    ]
