# Generated by Django 3.0.7 on 2020-09-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_quiz_check_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='check_score',
            field=models.BooleanField(default=True, verbose_name='check score'),
        ),
    ]
