# Generated by Django 3.0.7 on 2020-09-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20200903_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='completed',
            field=models.BooleanField(default=False, help_text='If quiz assessment is enabled, this field represents if the participant achieved a passing score or not.', verbose_name='completed successfully'),
        ),
    ]
