# Generated by Django 3.1.8 on 2021-05-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_auto_20201118_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='max_score',
            field=models.PositiveIntegerField(default=0, verbose_name='max score'),
        ),
    ]
