# Generated by Django 3.1.8 on 2021-05-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_quizscore_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.PositiveIntegerField(default=1, help_text='Value to add to quiz score if the participant answer the question correctly.', verbose_name='value'),
        ),
    ]
