# Generated by Django 3.1.8 on 2021-05-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_question_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.PositiveIntegerField(default=1, help_text='Value to add to the quiz score if the participant answer the question correctly.', verbose_name='value'),
        ),
    ]
