# Generated by Django 3.1.8 on 2021-05-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0043_auto_20210513_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='attempt number'),
        ),
    ]
