# Generated by Django 3.1.8 on 2021-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0044_quizscore_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_score',
            field=models.PositiveIntegerField(default=0, help_text='Maximum score automatically based on questions values.', verbose_name='max score'),
        ),
    ]
