# Generated by Django 3.1.8 on 2021-05-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0045_quiz_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='num_mistakes',
            field=models.PositiveIntegerField(default=0, help_text='Total number of mistakes (incorrect questions).', verbose_name='number of mistakes'),
        ),
    ]
