# Generated by Django 3.1.8 on 2021-05-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0046_quizscore_num_mistakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='attempt_number',
            field=models.PositiveIntegerField(default=0, verbose_name='attempt number'),
        ),
    ]
