# Generated by Django 3.1.8 on 2021-05-15 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_auto_20210515_1521'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0048_auto_20210514_2327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizscore',
            unique_together={('student', 'course', 'quiz')},
        ),
    ]
