# Generated by Django 3.1.8 on 2021-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_auto_20210515_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='assessment_method',
            field=models.CharField(blank=True, choices=[('MP', 'Minimum Percentage'), ('MN', 'Maximum Number of Mistakes')], help_text='method for assessing if the quiz has been', max_length=2, null=True, verbose_name='assessment method'),
        ),
    ]
