# Generated by Django 3.1.8 on 2021-05-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0050_auto_20210519_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='randomize',
            field=models.BooleanField(default=False, help_text='Randomize questions order', verbose_name='randomize'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='require_answers',
            field=models.BooleanField(default=False, help_text='Require participant to answer all questions', verbose_name='require answers'),
        ),
    ]
