# Generated by Django 3.1.8 on 2021-05-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_auto_20210519_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subset',
            field=models.BooleanField(default=False, help_text='Enable to use only a subset of the questions of this quiz', verbose_name='subset'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subset_number',
            field=models.PositiveIntegerField(default=0, help_text='Number of questions to use on the subset', verbose_name='subset'),
        ),
    ]
