# Generated by Django 3.1.8 on 2021-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0052_auto_20210520_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_score',
            field=models.PositiveIntegerField(default=0, help_text='** NOT IN USE ** Maximum score automatically based on questions values.', verbose_name='max score'),
        ),
    ]
