# Generated by Django 3.1.13 on 2021-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0057_auto_20210728_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='openended_type',
            field=models.CharField(choices=[('OD', 'Open ended - Date'), ('ON', 'Open ended - Numeric'), ('OH', 'Open ended - Time/hour'), ('OT', 'Open ended - Text (short)'), ('OA', 'Open ended - Text (long)'), ('OE', 'Open ended - Email')], default='OA', help_text='Type of open ended question.', max_length=2, verbose_name='Open ended type'),
        ),
    ]
