# Generated by Django 3.2.7 on 2021-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0060_auto_20210921_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='expert_feedback',
            field=models.BooleanField(default=False, help_text='Defines if the quiz was submitted by an expert/instructor.', verbose_name='expert feedback'),
        ),
    ]
