# Generated by Django 3.2.7 on 2021-09-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0061_quizscore_expert_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='answer_content',
            field=models.TextField(blank=True, null=True, verbose_name='Participant answer'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='multiplechoice_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.mcanswer', verbose_name='multiple choice item'),
        ),
    ]
