# Generated by Django 3.2.7 on 2022-01-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0062_auto_20210930_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_question_value',
            field=models.BooleanField(default=True, verbose_name='show question value'),
        ),
    ]
