# Generated by Django 3.2.12 on 2022-03-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0063_quiz_show_question_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explanation',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='explanation_en',
            new_name='feedback_en',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='explanation_fr',
            new_name='feedback_fr',
        ),
    ]
