# Generated by Django 3.2.12 on 2022-04-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0066_auto_20220329_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_question_number',
            field=models.BooleanField(default=True, verbose_name='Show question number'),
        ),
    ]
