# Generated by Django 3.2.13 on 2022-04-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0067_quiz_show_question_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="check_score",
            new_name="graded",
        ),
    ]
