# Generated by Django 3.2.13 on 2022-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0068_rename_check_score_quiz_graded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="graded",
            field=models.BooleanField(
                default=True,
                help_text="Defines if the quiz will be graded.",
                verbose_name="graded quiz",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="show_score",
            field=models.BooleanField(
                default=False,
                help_text="Defines if the quiz score and assessment will be shown in the results page.",
                verbose_name="show score",
            ),
        ),
    ]
