# Generated by Django 4.0.4 on 2022-05-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0069_auto_20220427_1849"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mcanswer",
            old_name="check",
            new_name="mark",
        ),
    ]
