# Generated by Django 4.0.7 on 2022-09-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_externalobject"),
        ("quiz", "0070_rename_check_mcanswer_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="feedback_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional feedback image file to be shown after the question has been answered.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedback_image",
                to="content.imagefile",
                verbose_name="feedback image",
            ),
        ),
    ]
