# Generated by Django 4.0.8 on 2022-12-17 19:53

import tinymce.models

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0071_question_feedback_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="Main text content of the question (max 1000 characters).",
                max_length=1000,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content_en",
            field=tinymce.models.HTMLField(
                help_text="Main text content of the question (max 1000 characters).",
                max_length=1000,
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content_fr",
            field=tinymce.models.HTMLField(
                help_text="Main text content of the question (max 1000 characters).",
                max_length=1000,
                null=True,
                verbose_name="content",
            ),
        ),
    ]
