# Generated by Django 4.0.8 on 2022-12-17 19:54

import tinymce.models

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0072_alter_question_content_alter_question_content_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="additional_content",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Optional: additional text that will be shown under the main text content. (max 1000 characters).",
                max_length=1000,
                null=True,
                verbose_name="additional content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="additional_content_en",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Optional: additional text that will be shown under the main text content. (max 1000 characters).",
                max_length=1000,
                null=True,
                verbose_name="additional content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="additional_content_fr",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Optional: additional text that will be shown under the main text content. (max 1000 characters).",
                max_length=1000,
                null=True,
                verbose_name="additional content",
            ),
        ),
    ]
