# Generated by Django 4.0.10 on 2023-04-06 16:44

import tinymce.models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0075_alter_mcanswer_content_alter_mcanswer_content_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcanswer",
            name="content",
            field=models.CharField(
                help_text="Enter the answer text that you want displayed (max 2000 characters).",
                max_length=2000,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="mcanswer",
            name="content_en",
            field=models.CharField(
                help_text="Enter the answer text that you want displayed (max 2000 characters).",
                max_length=2000,
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="mcanswer",
            name="content_fr",
            field=models.CharField(
                help_text="Enter the answer text that you want displayed (max 2000 characters).",
                max_length=2000,
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="additional_content",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Optional: additional text that will be shown under the main text content (max 2000 characters).",
                max_length=2000,
                null=True,
                verbose_name="additional content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="additional_content_en",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Optional: additional text that will be shown under the main text content (max 2000 characters).",
                max_length=2000,
                null=True,
                verbose_name="additional content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="additional_content_fr",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Optional: additional text that will be shown under the main text content (max 2000 characters).",
                max_length=2000,
                null=True,
                verbose_name="additional content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="Main text content of the question (max 2000 characters).",
                max_length=2000,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content_en",
            field=tinymce.models.HTMLField(
                help_text="Main text content of the question (max 2000 characters).",
                max_length=2000,
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content_fr",
            field=tinymce.models.HTMLField(
                help_text="Main text content of the question (max 2000 characters).",
                max_length=2000,
                null=True,
                verbose_name="content",
            ),
        ),
    ]
