# Generated by Django 4.2.6 on 2023-10-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_alter_videofile_subtitle_alter_videofile_subtitle_en_and_more'),
        ('quiz', '0076_alter_mcanswer_content_alter_mcanswer_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='feedback_video',
            field=models.ForeignKey(blank=True, help_text='Optional feedback video file to be shown after the question has been answered.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_video', to='videos.videofile', verbose_name='feedback_video'),
        ),
    ]
