# Generated by Django 4.2.6 on 2023-10-06 15:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0077_question_feedback_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='feedback',
            field=tinymce.models.HTMLField(blank=True, help_text='Feedback to be shown after the quiz has been answered.', verbose_name='feedback'),
        ),
    ]
