# Generated by Django 4.2.8 on 2023-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0079_quiz_show_submissions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='limit_submissions',
            field=models.BooleanField(default=False, help_text='Defines if the quiz should be disabled after reaching a specific number of submissions.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='limit_submissions_max',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of submissions allowed for the quiz.', verbose_name='Limit number of submissions'),
        ),
    ]
