# Generated by Django 2.1.5 on 2019-01-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20190117_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='author',
        ),
        migrations.RemoveField(
            model_name='media',
            name='forum',
        ),
        migrations.AddField(
            model_name='forum',
            name='kind',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('YTB', 'Youtube Video')], default='YTB', max_length=3),
        ),
        migrations.AddField(
            model_name='forum',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=ImMOdTxtf-s'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
