# Generated by Django 3.0.3 on 2020-05-19 18:15

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('sectionitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.SectionItem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=videos.models.user_directory_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=videos.models.user_directory_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.sectionitem',),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('sectionitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.SectionItem')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videolists', to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.sectionitem',),
        ),
    ]
