# Generated by Django 3.0.3 on 2020-05-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_section_published'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('sectionitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.SectionItem')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videolists', to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.sectionitem',),
        ),
        migrations.AddField(
            model_name='videofile',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='videos.Playlist'),
        ),
    ]
