# Generated by Django 3.0.3 on 2020-05-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200518_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videofile',
            options={'ordering': ['custom_order']},
        ),
        migrations.AddField(
            model_name='videofile',
            name='custom_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
