# Generated by Django 3.0.3 on 2020-05-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_section_published'),
        ('videos', '0003_auto_20200518_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='custom_order',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='title',
        ),
        migrations.AddField(
            model_name='videofile',
            name='sectionitem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.SectionItem'),
            preserve_default=False,
        ),
    ]
