# Generated by Django 3.0.3 on 2020-06-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20200610_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='original_name',
        ),
        migrations.AddField(
            model_name='videofile',
            name='internal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='video internal name (not visible to users)'),
        ),
    ]
