# Generated by Django 3.0.7 on 2020-06-15 17:03

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200615_1624'),
        ('videos', '0004_auto_20200610_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videolists', to='courses.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='courses.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to=videos.models.user_directory_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='internal_name',
            field=models.CharField(blank=True, help_text='video internal name (not visible to users)', max_length=255, null=True, verbose_name='internal name'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=videos.models.user_directory_path, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='uploaded at'),
        ),
    ]
