# Generated by Django 3.0.7 on 2020-06-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20200615_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'playlist', 'verbose_name_plural': 'playlists'},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'verbose_name': 'video file', 'verbose_name_plural': 'video files'},
        ),
    ]
