# Generated by Django 3.1.3 on 2020-11-30 18:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20200701_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
