# Generated by Django 3.0.7 on 2020-07-01 21:13

import django.core.validators
from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20200615_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to=videos.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'm4v', 'mov'))], verbose_name='file'),
        ),
    ]
