# Generated by Django 3.0.7 on 2020-07-01 21:36

from django.db import migrations, models
import upload_validator
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20200701_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(upload_to=videos.models.user_directory_path, validators=[upload_validator.FileTypeValidator(allowed_types=['video/mp4', 'video/quicktime'])], verbose_name='file'),
        ),
    ]
