# Generated by Django 3.1.12 on 2021-06-16 02:04

from django.db import migrations, models
import upload_validator
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_videofile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to=videos.models.user_directory_path, validators=[upload_validator.FileTypeValidator(allowed_types=['text/plain'])], verbose_name='subtitle'),
        ),
    ]
