# Generated by Django 3.2.13 on 2022-04-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_videofile_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='internal_name',
            field=models.CharField(blank=True, help_text='Video internal name (not visible to users).', max_length=255, null=True, verbose_name='internal name'),
        ),
    ]
