# Generated by Django 3.2.13 on 2022-04-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0012_moving_data_to_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videofile",
            name="content",
        ),
    ]
