# Generated by Django 4.0.6 on 2022-07-11 16:36

import core.support_methods
import upload_validator

import GEN.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0013_remove_videofile_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="file",
            field=models.FileField(
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=["video/mp4", "video/quicktime"]
                    )
                ],
                verbose_name="file",
            ),
        ),
    ]
