# Generated by Django 4.0.6 on 2022-07-16 20:33

import core.support_methods
import upload_validator

import GEN.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0014_alter_videofile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="subtitle",
            field=models.FileField(
                blank=True,
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(allowed_types=["text/plain"])
                ],
                verbose_name="subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                verbose_name="thumbnail",
            ),
        ),
    ]
