# Generated by Django 4.0.10 on 2023-04-06 17:15

import core.support_methods
import upload_validator

import GEN.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0015_alter_videofile_subtitle_alter_videofile_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofile",
            name="file_en",
            field=models.FileField(
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=["video/mp4", "video/quicktime"]
                    )
                ],
                verbose_name="file",
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="file_fr",
            field=models.FileField(
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=["video/mp4", "video/quicktime"]
                    )
                ],
                verbose_name="file",
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="subtitle_en",
            field=models.FileField(
                blank=True,
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(allowed_types=["text/plain"])
                ],
                verbose_name="subtitle",
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="subtitle_fr",
            field=models.FileField(
                blank=True,
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(allowed_types=["text/plain"])
                ],
                verbose_name="subtitle",
            ),
        ),
    ]
