# Generated by Django 4.0.10 on 2023-04-06 17:56

import core.support_methods
import upload_validator

import GEN.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0016_videofile_file_en_videofile_file_fr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="subtitle",
            field=models.FileField(
                blank=True,
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=["text/plain", "text/vtt"]
                    )
                ],
                verbose_name="subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="subtitle_en",
            field=models.FileField(
                blank=True,
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=["text/plain", "text/vtt"]
                    )
                ],
                verbose_name="subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="subtitle_fr",
            field=models.FileField(
                blank=True,
                null=True,
                storage=GEN.storage_backends.PrivateMediaStorage(),
                upload_to=core.support_methods.user_directory_path,
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=["text/plain", "text/vtt"]
                    )
                ],
                verbose_name="subtitle",
            ),
        ),
    ]
