# Generated by Django 4.2.16 on 2024-09-13 19:35

import GEN.storage_backends
from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_videofile_mute_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(storage=GEN.storage_backends.PrivateMediaStorage(), upload_to='', validators=[upload_validator.FileTypeValidator(allowed_types=['video/mp4', 'video/quicktime'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file_en',
            field=models.FileField(null=True, storage=GEN.storage_backends.PrivateMediaStorage(), upload_to='', validators=[upload_validator.FileTypeValidator(allowed_types=['video/mp4', 'video/quicktime'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file_fr',
            field=models.FileField(null=True, storage=GEN.storage_backends.PrivateMediaStorage(), upload_to='', validators=[upload_validator.FileTypeValidator(allowed_types=['video/mp4', 'video/quicktime'])], verbose_name='file'),
        ),
    ]
