# Generated by Django 4.2.16 on 2024-09-18 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_alter_videofile_file_alter_videofile_file_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='file_fr',
        ),
    ]
