# Generated by Django 4.2.16 on 2024-09-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_remove_videofile_file_en_remove_videofile_file_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
