# Generated by Django 4.2.16 on 2024-09-18 23:39

import GEN.storage_backends
from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_videofile_original_file_name_videofile_s3_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=GEN.storage_backends.PrivateMediaStorage(), upload_to='', validators=[upload_validator.FileTypeValidator(allowed_types=['video/mp4', 'video/quicktime'])], verbose_name='file'),
        ),
    ]
