# Generated by Django 3.1.8 on 2021-05-20 22:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0051_auto_20210520_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('sectionitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.sectionitem')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.sectionitem',),
        ),
    ]
