# Generated by Django 3.1.8 on 2021-05-20 23:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='content_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
