# Generated by Django 3.1.8 on 2021-05-22 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210520_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchColumnsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item name', max_length=100, verbose_name='name')),
                ('name_en', models.CharField(help_text='Item name', max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(help_text='Item name', max_length=100, null=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='MatchColumnsGame',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentitem')),
                ('source_column_name', models.CharField(default='Source column', help_text='Source column name', max_length=100, verbose_name='source column name')),
                ('choice1_column_name', models.CharField(default='Choice 1 column', help_text='Choice 1 column name', max_length=100, verbose_name='choice 1 column name')),
                ('choice2_column_name', models.CharField(default='Choice 2 column', help_text='Choice 2 column name', max_length=100, verbose_name='choice 1 column name')),
                ('choice1_column_items', models.ManyToManyField(help_text='List of items that are part of this column.', related_name='choice1_column_items', to='content.MatchColumnsItem', verbose_name='choice 1 column items')),
                ('choice2_column_items', models.ManyToManyField(help_text='List of items that are part of this column.', related_name='choice2_column_items', to='content.MatchColumnsItem', verbose_name='choice 2 column items')),
                ('source_column_items', models.ManyToManyField(help_text='List of items that are part of this column.', related_name='source_column_items', to='content.MatchColumnsItem', verbose_name='source column items')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.contentitem',),
        ),
        migrations.CreateModel(
            name='MatchColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Column name', max_length=100, verbose_name='name')),
                ('name_en', models.CharField(help_text='Column name', max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(help_text='Column name', max_length=100, null=True, verbose_name='name')),
                ('items', models.ManyToManyField(help_text='List of items that are part of this column.', related_name='item', to='content.MatchColumnsItem', verbose_name='items')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
