# Generated by Django 3.1.8 on 2021-05-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_delete_matchcolumn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchColumnsGame',
        ),
        migrations.DeleteModel(
            name='MatchColumnsItem',
        ),
    ]
