# Generated by Django 3.1.13 on 2021-09-18 18:59

import core.support_methods
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_auto_20210904_1823'),
        ('content', '0005_auto_20210530_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('sectionitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.sectionitem')),
                ('file', models.ImageField(help_text='Image file.', upload_to=core.support_methods.user_directory_path, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.sectionitem',),
        ),
    ]
