# Generated by Django 3.2.13 on 2022-04-28 15:25

from django.db import migrations


def move_data(apps, schema_editor):
    ContentItem = apps.get_model("content", "ContentItem")
    for item in ContentItem.objects.all():
        item.description = item.content
        item.description_en = item.description
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_pdffile"),
    ]

    operations = [migrations.RunPython(move_data)]
