# Generated by Django 4.0.4 on 2022-06-01 18:13

import core.support_methods
import upload_validator

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0083_alter_sectionitem_item_type"),
        ("content", "0009_auto_20220428_1610"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalObject",
            fields=[
                (
                    "sectionitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="courses.sectionitem",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Format accepted: zip. An 'index.html' file needs to exist in the root of the zip file.",
                        upload_to=core.support_methods.user_directory_path_not_random,
                        validators=[
                            upload_validator.FileTypeValidator(
                                allowed_types=["application/zip"]
                            )
                        ],
                        verbose_name="Zip package",
                    ),
                ),
                (
                    "directory",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="directory"
                    ),
                ),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("courses.sectionitem",),
        ),
    ]
