tasks:
  - init: |
      echo 'Build GEN docker image'
      docker-compose build
    command: |
      echo 'Start GEN'
      docker-compose up

vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - batisteo.vscode-django
    - eamodio.gitlens
    - mhutchie.git-graph
