tasks:
  - init: |
      echo 'Build GEN docker image'
      docker-compose -f "/workspace/GEN/docker-compose.yml" -f "/workspace/GEN/docker-compose.debug.yml" --build
    command: |
      echo 'Start GEN'
      docker-compose -f "/workspace/GEN/docker-compose.yml" -f "/workspace/GEN/docker-compose.debug.yml" up --detach 

vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - batisteo.vscode-django
    - eamodio.gitlens
    - mhutchie.git-graph
