version: '3'

services:
  gen:
    container_name: gen
    user: 1000:1000 
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "on-failure" 
    env_file: ./config/.env-dev
    volumes:
      - ./app:/gen/app
      - ./static:/gen/static
      - ./media:/gen/media
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - postgres

  postgres:
    image: "postgres:13"
    ports:
      - 5432:5432
    env_file: ./config/.env-dev
    volumes:
    - "postgres:/var/lib/postgresql/data/"

volumes:
  postgres:
