version: '3'

services:
  gen:
    container_name: gen
    user: 1000:1000
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "on-failure"
    env_file: ./config/dev.env
    volumes:
      - ./app:/gen/app
      - ./static:/gen/static
      - ./media:/gen/media
    command: gunicorn GEN.asgi:application --workers 2 --bind :8000 --worker-class uvicorn.workers.UvicornWorker --worker-tmp-dir /dev/shm --log-level Info --timeout 1000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:13"
    ports:
      - "5432:5432"
    env_file: ./config/dev.env
    volumes:
    - "postgres:/var/lib/postgresql/data/"

volumes:
  postgres:
