version: '3'

services:
  gen:
    container_name: gen
    user: $UID:$GID
    build:
      context: .
    restart: "on-failure" 
    env_file: ./config/env-dev-local
    volumes:
      - ./app:/gen/app:rw
      - ./static:/gen/static
      - ./media:/gen/media
    command: gunicorn GEN.asgi:application --workers 2 --bind :8000 --worker-class uvicorn.workers.UvicornWorker
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: 'postgres:13'
    ports:
      - 5432:5432
    env_file: ./config/env-dev-local
    volumes:
    - ./db-data/:/var/lib/postgresql/data/

