apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gen.fullname" . }}-configmap
  labels:
    {{- include "gen.labels" . | nindent 4 }}
data:
  # In a production environment, DO NOT set DJANGO_ALLOWED_HOSTS to *
  # It should represent the host/domain names that Django can serve
  DJANGO_ALLOWED_HOSTS: ".maxsimgen.com"
  DJANGO_INTERNAL_IPS: "127.0.0.1"
  DJANGO_LOGLEVEL: "info"
  DJANGO_DEBUG: "False"
  CSRF_COOKIE_DOMAIN: ".maxsimgen.com"
  CSRF_TRUSTED_ORIGINS: "https://*.maxsimgen.com"
  # Database
  POSTGRES_DB: "gen_www"
  DATABASE_SERVICE: "private-db-postgresql-tor1-98842-do-user-358345-0.b.db.ondigitalocean.com"
  DATABASE_PORT: "25060"
  DATABASE_OPTIONS: '{"sslmode": "require"}'
  # S3 storage
  USE_S3: "True"
  GEN_INSTANCE_NAME: "gen-www"
  STATIC_ENDPOINT_URL: "https://nyc3.digitaloceanspaces.com"
  STATIC_BUCKET_NAME: "gen-data"
  # Email
  DJANGO_ADMIN_EMAIL: "admin@maxsimgen.com"
  SERVER_EMAIL: "system@maxsimgen.com"
  DEFAULT_FROM_EMAIL: "donotreply@maxsimgen.com"
  SUPPORT_EMAILS: "support@maxsimgen.com"
  USE_EMAIL_DOMAINS_WHITELIST: "True"
  VALID_EMAIL_DOMAINS: "maxsimgen,ontariotechu,umontreal"
  # Social auth
  USE_SOCIAL_AUTH: "True"
  USE_SOCIAL_AUTH_ONLY: "False"
  USE_SOCIAL_AUTH_WHITELIST: "False"
  # NOTE: if Social Authentication is enabled, at least ONE provider should be listed.
  # Possible values: google, azuread (microsoft)
  SOCIAL_AUTH_PROVIDERS: "google,azuread"
  SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS: ""
  SOCIAL_AUTH_AZUREAD_OAUTH2_WHITELISTED_DOMAINS: ""
