apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gen.fullname" . }}
  labels:
    {{- include "gen.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gen.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "gen.fullname" . }}-configmap
          env:
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: DJANGO_SECRET_KEY
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: POSTGRES_PASSWORD
          - name: STATIC_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: STATIC_ACCESS_KEY_ID
          - name: STATIC_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: STATIC_SECRET_KEY
          - name: SOCIAL_AUTH_GITHUB_KEY
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: SOCIAL_AUTH_GITHUB_KEY
          - name: SOCIAL_AUTH_GITHUB_SECRET
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: SOCIAL_AUTH_GITHUB_SECRET
          - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
          - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: SENDGRID_API_KEY
          - name: SCORM_CLOUD_APP_ID
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: SCORM_CLOUD_APP_ID
          - name: SCORM_CLOUD_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: gen-secrets
                key: SCORM_CLOUD_SECRET_KEY
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
