# Generated by Django 3.0.3 on 2020-06-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200608_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openended',
            name='question_ptr',
        ),
        migrations.DeleteModel(
            name='MCQuestion',
        ),
        migrations.DeleteModel(
            name='OpenEnded',
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
            ],
            options={
                'verbose_name': 'Multiple choice question',
                'verbose_name_plural': 'Multiple choice questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='OpenEnded',
            fields=[
            ],
            options={
                'verbose_name': 'Open ended question',
                'verbose_name_plural': 'Open ended questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('quiz.question',),
        ),
    ]
