# Generated by Django 3.0.3 on 2020-06-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200608_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_correct_answers',
            field=models.BooleanField(default=False, help_text='Does this question have multiple correct answers             (allow user to select multiple answer items)?'),
        ),
    ]
