# Generated by Django 2.1.5 on 2019-01-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190126_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quiz.Quiz', verbose_name='Quiz'),
        ),
    ]
