# Generated by Django 2.1.5 on 2019-01-27 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0016_auto_20190125_2126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20190126_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQuestionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('correct', models.NullBooleanField()),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forums.Course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.MCQuestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'multiple choice question attempt',
                'verbose_name_plural': 'multiple choice question attempts',
            },
        ),
    ]
