# Generated by Django 2.1.5 on 2019-01-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_mcquestionattempt_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestionattempt',
            name='answer',
            field=models.CharField(default=' ', max_length=100, verbose_name='student answer'),
            preserve_default=False,
        ),
    ]
