# Generated by Django 2.1.5 on 2019-01-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_mcquestionattempt_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestionattempt',
            name='answer',
            field=models.CharField(max_length=1000, verbose_name='student answer'),
        ),
    ]
