# Generated by Django 2.1.5 on 2019-01-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190130_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcquestionattempt',
            old_name='attempt',
            new_name='attempt_no',
        ),
    ]
