# Generated by Django 2.1.5 on 2019-02-02 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0016_auto_20190125_2126'),
        ('quiz', '0010_auto_20190131_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forums.Course')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mcquestionattempt',
            options={'verbose_name': 'Multiple Choice Questions Attempt', 'verbose_name_plural': 'Multiple Choice Questions Attempts'},
        ),
    ]
