# Generated by Django 3.0.3 on 2020-06-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200610_1732'),
        ('quiz', '0011_questionattempt_multiplechoice_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='video_name',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='videos.VideoFile'),
        ),
    ]
