# Generated by Django 3.0.7 on 2020-06-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200523_1329'),
        ('quiz', '0012_auto_20200610_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.Section'),
            preserve_default=False,
        ),
    ]
