# Generated by Django 2.1.5 on 2019-02-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quizscore_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestionattempt',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course'),
        ),
    ]
