# Generated by Django 2.2 on 2019-12-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20190213_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestionattempt',
            name='answer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='quiz.Answer'),
            preserve_default=False,
        ),
    ]
