# Generated by Django 2.2 on 2019-12-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_mcquestionattempt_answer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcquestionattempt',
            old_name='answer',
            new_name='answer_content',
        ),
    ]
