# Generated by Django 2.2 on 2019-12-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20191219_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcquestionattempt',
            old_name='answer_id',
            new_name='answer',
        ),
    ]
