# Generated by Django 3.0.3 on 2020-03-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0024_auto_20200321_2042'),
        ('quiz', '0016_auto_20191219_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='forums.VideoFile'),
        ),
    ]
