# Generated by Django 3.0.3 on 2020-04-12 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20200321_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likert',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
            ],
            options={
                'verbose_name': 'Likert scale question',
                'verbose_name_plural': 'Likert scale questions',
            },
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='LikertAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('correct', models.CharField(blank=True, choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=2, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Likert')),
            ],
            options={
                'verbose_name': 'Likert answer',
                'verbose_name_plural': 'Likert answers',
            },
        ),
    ]
