# Generated by Django 3.0.3 on 2020-04-12 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0018_likert_likertanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikertAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('correct', models.NullBooleanField()),
                ('no_of_attempt', models.PositiveIntegerField(default=1)),
                ('scale', models.CharField(blank=True, choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=2, null=True)),
                ('likert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Likert')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'likert scale attempt',
                'verbose_name_plural': 'likert scale attempts',
            },
        ),
    ]
