# Generated by Django 3.0.7 on 2020-06-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20200615_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcanswer',
            options={'ordering': ['custom_order'], 'verbose_name': 'multiple choice answer', 'verbose_name_plural': 'multiple choice answers'},
        ),
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': 'multiple choice question', 'verbose_name_plural': 'multiple choice questions'},
        ),
        migrations.AlterModelOptions(
            name='openended',
            options={'verbose_name': 'open ended question', 'verbose_name_plural': 'open ended questions'},
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='content',
            field=models.CharField(help_text='Enter the answer text that you want displayed', max_length=1000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='correct',
            field=models.BooleanField(default=False, help_text='Is this the correct answer?', verbose_name='correct'),
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='custom order'),
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.MCQuestion', verbose_name='question'),
        ),
    ]
