# Generated by Django 3.0.3 on 2020-04-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_openended_openendedattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openended',
            options={'verbose_name': 'Open ended Question', 'verbose_name_plural': 'Open ended questions'},
        ),
    ]
