# Generated by Django 3.0.3 on 2020-04-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20200412_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likertattempt',
            old_name='no_of_attempt',
            new_name='attempt_number',
        ),
        migrations.RenameField(
            model_name='mcquestionattempt',
            old_name='attempt_no',
            new_name='attempt_number',
        ),
        migrations.RenameField(
            model_name='openendedattempt',
            old_name='no_of_attempt',
            new_name='attempt_number',
        ),
    ]
