# Generated by Django 3.0.7 on 2020-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20200615_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_en',
            field=models.CharField(help_text='Enter the content that you want displayed.', max_length=1000, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='question',
            name='content_fr',
            field=models.CharField(help_text='Enter the content that you want displayed.', max_length=1000, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_en',
            field=models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', null=True, verbose_name='explanation'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_fr',
            field=models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', null=True, verbose_name='explanation'),
        ),
    ]
