# Generated by Django 3.0.3 on 2020-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20200427_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertanswer',
            name='correct',
        ),
        migrations.AddField(
            model_name='likertanswer',
            name='scale_max',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='likertanswer',
            name='scale_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likertattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='openendedattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
