# Generated by Django 3.0.3 on 2020-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20200427_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likertanswer',
            name='scale_min',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
