# Generated by Django 3.0.3 on 2020-04-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20200427_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likertanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='quiz.Likert'),
        ),
    ]
