# Generated by Django 3.0.7 on 2020-06-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20200622_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='multiplechoice_answers',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='multiplechoice_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.MCAnswer', verbose_name='multiple choice answers'),
        ),
    ]
