# Generated by Django 3.0.3 on 2020-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20200427_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertanswer',
            options={'verbose_name': 'Likert answer (scale)', 'verbose_name_plural': 'Likert answers (scales)'},
        ),
        migrations.RemoveField(
            model_name='likertattempt',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='likertattempt',
            name='scale',
        ),
        migrations.AddField(
            model_name='likertattempt',
            name='scale_answer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
