# Generated by Django 3.0.3 on 2020-04-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20200428_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likert',
            options={'verbose_name': 'Likert Scale Question', 'verbose_name_plural': 'Likert Scale Questions'},
        ),
        migrations.AlterModelOptions(
            name='likertanswer',
            options={'verbose_name': 'Likert Answer (scale)', 'verbose_name_plural': 'Likert Answers (scales)'},
        ),
        migrations.AlterModelOptions(
            name='likertattempt',
            options={'verbose_name': 'Likert Scale Attempt', 'verbose_name_plural': 'Likert Scale Attempts'},
        ),
        migrations.AlterModelOptions(
            name='openendedattempt',
            options={'verbose_name': 'Open Ended Attempt', 'verbose_name_plural': 'Open Ended Attempts'},
        ),
        migrations.RenameField(
            model_name='likertattempt',
            old_name='likert',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='openendedattempt',
            old_name='openended',
            new_name='question',
        ),
    ]
