# Generated by Django 3.0.3 on 2020-04-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20200428_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='MCAnswer',
        ),
    ]
