# Generated by Django 3.0.3 on 2020-04-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20200428_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroupHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter a text for the question group. It will work as a title.', max_length=1000)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz')),
            ],
        ),
    ]
