# Generated by Django 3.0.7 on 2020-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_quiz_allow_multiple_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assessment_method',
            field=models.CharField(choices=[('NO', 'None'), ('MP', 'Minimum Percentage'), ('MN', 'Maximum Number of Mistakes')], default='NO', max_length=2, verbose_name='method for assessing if the quiz has been '),
        ),
    ]
