# Generated by Django 3.0.3 on 2020-04-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_questiongroupheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroupheader',
            name='content',
        ),
        migrations.RemoveField(
            model_name='questiongroupheader',
            name='id',
        ),
        migrations.RemoveField(
            model_name='questiongroupheader',
            name='quiz',
        ),
        migrations.AddField(
            model_name='questiongroupheader',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question'),
            preserve_default=False,
        ),
    ]
