# Generated by Django 3.0.3 on 2020-04-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20200429_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='Enter the content that you want displayed.', max_length=1000, verbose_name='Content'),
        ),
    ]
