# Generated by Django 3.0.3 on 2020-04-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_auto_20200429_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quiz.Quiz', verbose_name='Quiz'),
            preserve_default=False,
        ),
    ]
