# Generated by Django 3.0.3 on 2020-04-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20200429_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likert',
            options={'verbose_name': 'Likert question', 'verbose_name_plural': 'Likert questions'},
        ),
        migrations.AlterModelOptions(
            name='likertanswer',
            options={'verbose_name': 'Likert answer (scale)', 'verbose_name_plural': 'Likert answers (scales)'},
        ),
        migrations.AlterModelOptions(
            name='likertattempt',
            options={'verbose_name': 'Likert attempt', 'verbose_name_plural': 'Likert attempts'},
        ),
        migrations.AlterModelOptions(
            name='mcanswer',
            options={'verbose_name': 'Multiple choice answer', 'verbose_name_plural': 'Multiple choice answers'},
        ),
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': 'Multiple choice question', 'verbose_name_plural': 'Multiple choice questions'},
        ),
        migrations.AlterModelOptions(
            name='mcquestionattempt',
            options={'verbose_name': 'Multiple choice questions attempt', 'verbose_name_plural': 'Multiple choice questions attempts'},
        ),
        migrations.AlterModelOptions(
            name='openended',
            options={'verbose_name': 'Open ended question', 'verbose_name_plural': 'Open ended questions'},
        ),
        migrations.AlterModelOptions(
            name='openendedattempt',
            options={'verbose_name': 'Open ended attempt', 'verbose_name_plural': 'Open ended attempts'},
        ),
    ]
