# Generated by Django 3.0.3 on 2020-04-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_auto_20200429_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertanswer',
            options={'verbose_name': 'Likert answer (scale definition)', 'verbose_name_plural': 'Likert answers (scale definition)'},
        ),
    ]
