# Generated by Django 3.1.3 on 2020-11-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_quizscore_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='correct'),
        ),
    ]
