# Generated by Django 3.0.3 on 2020-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_auto_20200429_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='likertanswer',
            name='legend',
            field=models.TextField(blank=True, help_text='Legend for the likert scale values.'),
        ),
    ]
