# Generated by Django 3.0.3 on 2020-04-30 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0026_videofile_thumbnail'),
        ('quiz', '0042_likertanswer_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='forums.VideoFile'),
        ),
    ]
