# Generated by Django 3.0.3 on 2020-04-30 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0044_auto_20200429_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='quiz.Quiz'),
        ),
    ]
