# Generated by Django 3.0.3 on 2020-04-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0046_questionattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertattempt',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='likertattempt',
            name='course',
        ),
        migrations.RemoveField(
            model_name='likertattempt',
            name='created',
        ),
        migrations.RemoveField(
            model_name='likertattempt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='likertattempt',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='likertattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='likertattempt',
            name='student',
        ),
        migrations.AddField(
            model_name='likertattempt',
            name='questionattempt_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.QuestionAttempt'),
            preserve_default=False,
        ),
    ]
