# Generated by Django 3.0.3 on 2020-05-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_auto_20200430_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts_max_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
