# Generated by Django 3.0.3 on 2020-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0051_auto_20200505_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquestion',
            name='multiple_correct_answers',
            field=models.BooleanField(default=False, help_text='Does this question have multiple correct answers             (allow user to select multiple answer items)?'),
        ),
    ]
