# Generated by Django 3.0.3 on 2020-05-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0052_mcquestion_multiple_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likertanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Likert'),
        ),
    ]
