# Generated by Django 3.0.3 on 2020-05-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0054_auto_20200512_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcanswer',
            options={'ordering': ['custom_order'], 'verbose_name': 'Multiple choice answer', 'verbose_name_plural': 'Multiple choice answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['custom_order']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['custom_order'], 'verbose_name_plural': 'quizzes'},
        ),
        migrations.RenameField(
            model_name='mcanswer',
            old_name='order',
            new_name='custom_order',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='custom_order',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='order',
            new_name='custom_order',
        ),
    ]
