# Generated by Django 3.0.3 on 2020-05-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0055_auto_20200512_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
