# Generated by Django 3.0.3 on 2020-05-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0056_auto_20200512_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likertattempt',
            old_name='scale_answer',
            new_name='answer_content',
        ),
        migrations.RenameField(
            model_name='openendedattempt',
            old_name='answer',
            new_name='answer_content',
        ),
    ]
