# Generated by Django 3.0.3 on 2020-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0057_auto_20200512_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_correct_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_score',
            field=models.BooleanField(default=False),
        ),
    ]
