# Generated by Django 3.0.3 on 2020-05-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('quiz', '0058_auto_20200513_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='videos.VideoFile'),
        ),
    ]
