# Generated by Django 3.0.3 on 2020-05-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200517_1959'),
        ('quiz', '0059_auto_20200513_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='courses.Section'),
        ),
    ]
