# Generated by Django 3.0.3 on 2020-05-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0061_auto_20200517_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz'),
        ),
    ]
