# Generated by Django 3.0.3 on 2020-05-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0062_auto_20200518_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_score',
            field=models.BooleanField(default=False),
        ),
    ]
