# Generated by Django 3.0.3 on 2020-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='show_progress_tracker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='show_scoreboard',
            field=models.BooleanField(default=True),
        ),
    ]
