# Generated by Django 3.0.3 on 2020-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200513_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enable_gamification',
            field=models.BooleanField(default=True),
        ),
    ]
