# Generated by Django 3.0.3 on 2020-05-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200523_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='create_discussions',
            field=models.BooleanField(default=False, help_text="* FOR UPLOAD SECTION ONLY *: automatically create a discussion board based on participant's video submissions."),
        ),
        migrations.AddField(
            model_name='section',
            name='section_output',
            field=models.ForeignKey(blank=True, help_text='* FOR UPLOAD SECTION ONLY *: Define the section in which to create the discussion boards.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections_output', to='courses.Section'),
        ),
    ]
