# Generated by Django 3.0.3 on 2020-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_enable_gamification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='show_leaderboard',
            field=models.BooleanField(default=True, help_text='Requires gamification'),
        ),
        migrations.AlterField(
            model_name='course',
            name='show_scoreboard',
            field=models.BooleanField(default=True, help_text='Requires gamification'),
        ),
    ]
