# Generated by Django 3.0.3 on 2020-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200513_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enable_gamification',
            field=models.BooleanField(default=True, help_text='Enables voting in forums and comments'),
        ),
    ]
