# Generated by Django 3.0.3 on 2020-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200513_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course code (max 10 characters)', max_length=10, verbose_name='course code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(help_text='Course description (max 400 characters)', max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Course name (max 100 characters)', max_length=100, unique=True),
        ),
    ]
