# Generated by Django 3.0.3 on 2020-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200513_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enable_gamification',
            field=models.BooleanField(default=True, help_text='Enables voting in forums and comments', verbose_name='gamification'),
        ),
    ]
