# Generated by Django 3.0.3 on 2020-05-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200513_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section name (max 15 characters)', max_length=15)),
                ('section_type', models.CharField(choices=[('D', 'Discussion boards'), ('V', 'Videos'), ('Q', 'Quizzes'), ('U', 'Uploads')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='courses.Course')),
            ],
        ),
    ]
