# Generated by Django 3.0.3 on 2020-05-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['custom_order']},
        ),
        migrations.AddField(
            model_name='section',
            name='custom_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
