# Generated by Django 3.0.3 on 2020-05-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200517_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['custom_order'], 'verbose_name_plural': 'sections'},
        ),
    ]
