# Generated by Django 3.0.3 on 2020-05-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200517_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
