# Generated by Django 3.0.7 on 2020-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200615_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description_en',
            field=models.TextField(blank=True, help_text='Course description (max 800 characters)', max_length=800, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Course description (max 800 characters)', max_length=800, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(help_text='Section name (max 15 characters)', max_length=15, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_fr',
            field=models.CharField(help_text='Section name (max 15 characters)', max_length=15, null=True, verbose_name='name'),
        ),
    ]
