# Generated by Django 3.0.3 on 2020-05-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_section_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
