# Generated by Django 3.0.3 on 2020-05-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_section_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, help_text='Course description (max 200 characters)', max_length=200, null=True),
        ),
    ]
