# Generated by Django 3.0.3 on 2020-05-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200518_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionitem',
            name='show_score',
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='description',
            field=models.CharField(help_text='Brief description (max 200 characters)', max_length=200),
        ),
    ]
