# Generated by Django 3.0.3 on 2020-05-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200518_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enable_gamification',
            field=models.BooleanField(default=True, help_text='Enables voting in discussions and comments', verbose_name='gamification'),
        ),
    ]
