# Generated by Django 3.0.7 on 2020-06-28 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0020_auto_20200615_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participant',
            field=models.ManyToManyField(related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
    ]
