# Generated by Django 3.0.7 on 2020-06-28 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0023_auto_20200628_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
    ]
