# Generated by Django 3.0.7 on 2020-07-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20200701_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Unique course code (max 10 characters)', max_length=10, unique=True, verbose_name='course code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Course name (max 100 characters)', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_en',
            field=models.CharField(help_text='Course name (max 100 characters)', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_fr',
            field=models.CharField(help_text='Course name (max 100 characters)', max_length=100, null=True, verbose_name='name'),
        ),
    ]
