# Generated by Django 3.0.7 on 2020-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20200712_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('D', 'Discussion boards'), ('V', 'Videos'), ('Q', 'Quizzes'), ('U', 'Uploads'), ('C', 'Content')], max_length=1, verbose_name='section type'),
        ),
    ]
