# Generated by Django 3.0.7 on 2020-07-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20200718_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Description (max 1000 characters)', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=models.TextField(help_text='Description (max 1000 characters)', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_fr',
            field=models.TextField(help_text='Description (max 1000 characters)', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Description (max 1000 characters)', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description (max 1000 characters)', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Description (max 1000 characters)', max_length=1000, null=True, verbose_name='description'),
        ),
    ]
