# Generated by Django 3.1.3 on 2020-11-20 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0038_auto_20201120_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
