# Generated by Django 3.1.3 on 2020-11-20 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0039_auto_20201120_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(help_text="List of instructors. These users will be able to edit the course's content and structure.", related_name='instructor', to=settings.AUTH_USER_MODEL, verbose_name='instructors'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learners',
            field=models.ManyToManyField(blank=True, help_text='List of learners (students).', related_name='learners', to=settings.AUTH_USER_MODEL, verbose_name='learners'),
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(help_text='List of all users that should have access to the course (including instructors).', related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
