# Generated by Django 3.1.3 on 2020-11-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_auto_20201130_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='show_related_content',
            field=models.BooleanField(default=False, help_text='Display content related to this item (e.g., quizzes related to a video)', verbose_name='show related content'),
        ),
    ]
