# Generated by Django 3.1.8 on 2021-05-30 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0051_auto_20210520_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('sectionitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.sectionitem')),
                ('type', models.CharField(choices=[('MC', 'Move to columns'), ('MT', 'Match terms'), ('TB', 'Text boxes')], max_length=2, verbose_name='game type')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.sectionitem',),
        ),
        migrations.CreateModel(
            name='TextBoxesTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Item text description (max 100 characters)', max_length=100, verbose_name='text')),
                ('text_en', models.CharField(help_text='Item text description (max 100 characters)', max_length=100, null=True, verbose_name='text')),
                ('text_fr', models.CharField(help_text='Item text description (max 100 characters)', max_length=100, null=True, verbose_name='text')),
                ('custom_order', models.PositiveIntegerField(default=0, verbose_name='custom order')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='TextBoxesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Item text description (max 400 characters)', max_length=400, verbose_name='text')),
                ('text_en', models.TextField(help_text='Item text description (max 400 characters)', max_length=400, null=True, verbose_name='text')),
                ('text_fr', models.TextField(help_text='Item text description (max 400 characters)', max_length=400, null=True, verbose_name='text')),
                ('custom_order', models.PositiveIntegerField(default=0, verbose_name='custom order')),
                ('correct_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.textboxesterm')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='MoveToColumnsGame',
            fields=[
            ],
            options={
                'verbose_name': 'Move to columns game',
                'verbose_name_plural': 'Move to columns games',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.game',),
        ),
        migrations.CreateModel(
            name='TextBoxesGame',
            fields=[
            ],
            options={
                'verbose_name': 'Complete the text boxes game',
                'verbose_name_plural': 'Complete the text boxes games',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.game',),
        ),
        migrations.CreateModel(
            name='MoveToColumnsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Item text description (max 100 characters)', max_length=100, verbose_name='text')),
                ('text_en', models.CharField(help_text='Item text description (max 100 characters)', max_length=100, null=True, verbose_name='text')),
                ('text_fr', models.CharField(help_text='Item text description (max 100 characters)', max_length=100, null=True, verbose_name='text')),
                ('custom_order', models.PositiveIntegerField(default=0, verbose_name='custom order')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.movetocolumnsgame')),
            ],
            options={
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='MoveToColumnsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='Source column', help_text='Source column name', max_length=100, verbose_name='source column name')),
                ('source_name_en', models.CharField(default='Source column', help_text='Source column name', max_length=100, null=True, verbose_name='source column name')),
                ('source_name_fr', models.CharField(default='Source column', help_text='Source column name', max_length=100, null=True, verbose_name='source column name')),
                ('choice1_name', models.CharField(default='Choice 1 column', help_text='Choice 1 column name', max_length=100, verbose_name='choice 1 column name')),
                ('choice1_name_en', models.CharField(default='Choice 1 column', help_text='Choice 1 column name', max_length=100, null=True, verbose_name='choice 1 column name')),
                ('choice1_name_fr', models.CharField(default='Choice 1 column', help_text='Choice 1 column name', max_length=100, null=True, verbose_name='choice 1 column name')),
                ('choice2_name', models.CharField(default='Choice 2 column', help_text='Choice 2 column name', max_length=100, verbose_name='choice 1 column name')),
                ('choice2_name_en', models.CharField(default='Choice 2 column', help_text='Choice 2 column name', max_length=100, null=True, verbose_name='choice 1 column name')),
                ('choice2_name_fr', models.CharField(default='Choice 2 column', help_text='Choice 2 column name', max_length=100, null=True, verbose_name='choice 1 column name')),
                ('choice1_items', models.ManyToManyField(help_text='List of items that are part of this column.', related_name='choice1_column_items', to='games.MoveToColumnsItem', verbose_name='choice 1 column items')),
                ('choice2_items', models.ManyToManyField(help_text='List of items that are part of this column.', related_name='choice2_column_items', to='games.MoveToColumnsItem', verbose_name='choice 2 column items')),
                ('source_items', models.ManyToManyField(help_text='List of items that are part of this column.', related_name='source_column_items', to='games.MoveToColumnsItem', verbose_name='source column items')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='columns', to='games.movetocolumnsgame')),
            ],
            options={
                'verbose_name': 'Move to columns game content',
                'verbose_name_plural': 'Move to columns games content',
            },
        ),
    ]
