# Generated by Django 3.1.8 on 2021-06-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTermsGame',
            fields=[
            ],
            options={
                'verbose_name': 'Match terms game',
                'verbose_name_plural': 'Match terms games',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.game',),
        ),
    ]
