# Generated by Django 4.0.4 on 2022-05-10 17:35

import sortedm2m.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_movetocolumnsgroup_source_shuffle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textboxesitem",
            name="correct_term",
        ),
        migrations.AddField(
            model_name="textboxesitem",
            name="correct_terms",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text="List of correct terms.",
                related_name="correct_term_items",
                to="games.textboxesterm",
                verbose_name="correct term items",
            ),
        ),
    ]
