# Generated by Django 4.0.4 on 2022-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_remove_textboxesitem_correct_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="shuffle",
            field=models.BooleanField(
                default=False,
                help_text="Defines if the source items should be shuffled.",
            ),
        ),
    ]
