# Generated by Django 4.0.4 on 2022-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_game_shuffle"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="show_numbers",
            field=models.BooleanField(
                default=True,
                help_text="Defines if the answer items should be numbered.",
            ),
        ),
    ]
