# Generated by Django 4.0.4 on 2022-05-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_alter_game_show_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textboxesitem",
            name="text",
            field=models.TextField(
                help_text="Item text description (max 500 characters)",
                max_length=500,
                verbose_name="text",
            ),
        ),
        migrations.AlterField(
            model_name="textboxesitem",
            name="text_en",
            field=models.TextField(
                help_text="Item text description (max 500 characters)",
                max_length=500,
                null=True,
                verbose_name="text",
            ),
        ),
        migrations.AlterField(
            model_name="textboxesitem",
            name="text_fr",
            field=models.TextField(
                help_text="Item text description (max 500 characters)",
                max_length=500,
                null=True,
                verbose_name="text",
            ),
        ),
    ]
