# Generated by Django 2.1.5 on 2019-01-17 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PDF', 'PDF Document'), ('YTB', 'Youtube Video')], default='YTB', max_length=3)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='forums.Forum')),
            ],
        ),
        migrations.RemoveField(
            model_name='attachmentkind',
            name='author',
        ),
        migrations.RemoveField(
            model_name='attachmentkind',
            name='forum',
        ),
        migrations.DeleteModel(
            name='AttachmentKind',
        ),
    ]
