# Generated by Django 2.1.5 on 2019-01-21 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20190118_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
