# Generated by Django 2.1.5 on 2019-01-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_forum_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
