# Generated by Django 2.1.5 on 2019-01-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_auto_20190121_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
