# Generated by Django 2.1.5 on 2019-01-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='forums', to='forums.Course'),
            preserve_default=False,
        ),
    ]
