# Generated by Django 2.1.5 on 2019-01-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0011_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='describe something here', max_length=100),
            preserve_default=False,
        ),
    ]
