# Generated by Django 2.1.5 on 2019-01-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0012_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('PDF', 'PDF Document'), ('YTB', 'Youtube Video')], default='YTB', max_length=3)),
                ('url', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='kind',
        ),
        migrations.AddField(
            model_name='forum',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='forums.MediaFile'),
            preserve_default=False,
        ),
    ]
