# Generated by Django 2.1.5 on 2019-01-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_remove_forum_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='name',
            new_name='title',
        ),
    ]
