# Generated by Django 2.1.5 on 2019-02-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20190213_1146'),
        ('forums', '0016_auto_20190125_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AlterField(
            model_name='forum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forums', to='courses.Course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
