# Generated by Django 3.0.3 on 2020-03-02 20:36

from django.db import migrations, models
import forums.models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0018_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='video',
            field=models.FileField(upload_to=forums.models.user_directory_path),
        ),
    ]
