# Generated by Django 3.0.3 on 2020-03-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0019_auto_20200302_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videofile',
            old_name='video',
            new_name='file',
        ),
    ]
