# Generated by Django 3.0.3 on 2020-03-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0020_auto_20200302_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='kind',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('YTB', 'Youtube Video'), ('MP4', 'Video Upload')], default='YTB', max_length=3),
        ),
    ]
