# Generated by Django 3.0.3 on 2020-03-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0021_auto_20200321_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='media',
        ),
        migrations.AddField(
            model_name='forum',
            name='video',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='forums', to='forums.VideoFile'),
            preserve_default=False,
        ),
    ]
