# Generated by Django 3.0.3 on 2020-03-22 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0023_auto_20200321_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forums', to='forums.VideoFile'),
        ),
    ]
