# Generated by Django 3.0.3 on 2020-04-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0024_auto_20200321_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='forums.VideoFile'),
        ),
    ]
