# Generated by Django 3.0.3 on 2020-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0026_videofile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
