# Generated by Django 3.0.3 on 2020-05-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('forums', '0027_auto_20200513_1732'),
        ('quiz', '0059_auto_20200513_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='videos.VideoFile'),
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
