# Generated by Django 3.0.3 on 2020-05-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200517_2102'),
        ('forums', '0028_auto_20200513_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='description',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='id',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
        migrations.AddField(
            model_name='forum',
            name='sectionitem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.SectionItem'),
            preserve_default=False,
        ),
    ]
