# Generated by Django 3.0.3 on 2020-05-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0029_auto_20200517_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forums.Forum'),
        ),
    ]
