# Generated by Django 3.0.3 on 2020-05-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0030_forum_requirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
