# Generated by Django 3.0.3 on 2020-05-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200518_1910'),
        ('courses', '0017_auto_20200518_2317'),
        ('forums', '0031_delete_mediafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('sectionitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.SectionItem')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussion', to='courses.Course')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forums.Discussion')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='videos.VideoFile')),
            ],
            options={
                'abstract': False,
            },
            bases=('courses.sectionitem', models.Model),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='forum',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forums.Discussion'),
            preserve_default=False,
        ),
    ]
