# Generated by Django 3.0.3 on 2020-05-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200518_1910'),
        ('courses', '0017_auto_20200518_2317'),
        ('forums', '0032_auto_20200519_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussions', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='videos.VideoFile'),
        ),
    ]
