# Generated by Django 3.0.3 on 2020-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200523_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Course description (max 800 characters)', max_length=800),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Course description (max 800 characters)', max_length=800, null=True),
        ),
    ]
