# Generated by Django 3.0.3 on 2020-05-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200523_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='description',
            field=models.TextField(help_text='Brief description (max 400 characters)', max_length=400),
        ),
    ]
