# Generated by Django 3.0.7 on 2020-06-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_section_show_thumbnails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Course description (max 800 characters)', max_length=800, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Course name (max 100 characters)', max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='show_leaderboard',
            field=models.BooleanField(default=True, help_text='Requires gamification', verbose_name='show leaderboard'),
        ),
        migrations.AlterField(
            model_name='course',
            name='show_progress_tracker',
            field=models.BooleanField(default=True, verbose_name='show progress tracker'),
        ),
        migrations.AlterField(
            model_name='course',
            name='show_scoreboard',
            field=models.BooleanField(default=True, help_text='Requires gamification', verbose_name='show scoreboard'),
        ),
    ]
