# Generated by Django 3.0.7 on 2020-06-15 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_auto_20200615_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionitem',
            options={'ordering': ['custom_order'], 'verbose_name': 'section item', 'verbose_name_plural': 'section items'},
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_items', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='custom order'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='description',
            field=models.TextField(help_text='Brief description (max 400 characters)', max_length=400, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='name',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_items', to='courses.Section', verbose_name='section'),
        ),
    ]
