# Generated by Django 3.0.7 on 2020-06-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200615_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='description_en',
            field=models.TextField(help_text='Brief description (max 400 characters)', max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='description_fr',
            field=models.TextField(help_text='Brief description (max 400 characters)', max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='name'),
        ),
    ]
