# Generated by Django 3.0.7 on 2020-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participants_max_number',
            field=models.IntegerField(blank=True, default=100, help_text='maximum number of participants', null=True, verbose_name='partipants max number'),
        ),
    ]
