# Generated by Django 3.0.7 on 2020-06-28 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0022_course_participants_max_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='course',
            name='participants_max_number',
            field=models.IntegerField(blank=True, help_text='maximum number of participants', null=True, verbose_name='partipants max number'),
        ),
    ]
