# Generated by Django 3.0.7 on 2020-07-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20200629_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='participants_max_number',
            field=models.IntegerField(blank=True, help_text='maximum number of participants', null=True, verbose_name='participants max number'),
        ),
    ]
