# Generated by Django 3.0.7 on 2020-07-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20200712_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Course description (max 1000 characters)', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=models.TextField(help_text='Course description (max 1000 characters)', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_fr',
            field=models.TextField(help_text='Course description (max 1000 characters)', max_length=1000, null=True, verbose_name='description'),
        ),
    ]
