# Generated by Django 3.0.7 on 2020-11-11 21:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20200727_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
