# Generated by Django 3.1.3 on 2020-11-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_section_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='participants',
            new_name='learners',
        ),
    ]
