# Generated by Django 3.1.3 on 2020-11-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20201120_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='participants_max_number',
            new_name='learners_max_number',
        ),
    ]
