# Generated by Django 3.1.3 on 2020-11-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20201120_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learners_max_number',
            field=models.IntegerField(blank=True, help_text='maximum number of learners', null=True, verbose_name='learners max number'),
        ),
    ]
