# Generated by Django 3.1.3 on 2020-11-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20201120_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='members',
        ),
    ]
