# Generated by Django 3.1.3 on 2021-01-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_auto_20201130_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Section name (max 20 characters)', max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name_en',
            field=models.CharField(help_text='Section name (max 20 characters)', max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name_fr',
            field=models.CharField(help_text='Section name (max 20 characters)', max_length=20, null=True, verbose_name='name'),
        ),
    ]
