# Generated by Django 3.1.3 on 2021-02-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20210119_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Description (max 1500 characters)', max_length=1500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=models.TextField(help_text='Description (max 1500 characters)', max_length=1500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_fr',
            field=models.TextField(help_text='Description (max 1500 characters)', max_length=1500, null=True, verbose_name='description'),
        ),
    ]
