# Generated by Django 3.1.8 on 2021-05-15 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0044_auto_20210209_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('completed', models.BooleanField(default=False, help_text='Whether the section has been marked as complete or not.', verbose_name='section completed successfully')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='learner')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'section status',
                'verbose_name_plural': 'sections status',
            },
        ),
    ]
