# Generated by Django 3.1.8 on 2021-05-15 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0045_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('learner', 'course', 'section')},
        ),
    ]
