# Generated by Django 3.1.8 on 2021-05-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_auto_20210516_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='status',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether the item has been marked as complete or not.', verbose_name='item completed successfully'),
        ),
        migrations.AlterField(
            model_name='status',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='courses.section', verbose_name='section'),
        ),
    ]
