# Generated by Django 3.1.8 on 2021-05-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_auto_20210519_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='final_assessment',
            field=models.BooleanField(default=False, help_text='* FOR QUIZ SECTION ONLY *: Is this section a final assessment to evaluate if the learner successfully completed the course/module?', verbose_name='final assessment'),
        ),
    ]
