# Generated by Django 3.1.8 on 2021-05-20 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0050_section_final_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='courses.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='status',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to=settings.AUTH_USER_MODEL, verbose_name='learner'),
        ),
    ]
