# Generated by Django 3.1.13 on 2021-07-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0053_auto_20210525_1546'),
        ('courses', '0051_auto_20210520_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='clone_quiz',
            field=models.BooleanField(default=False, help_text="* FOR UPLOAD SECTION ONLY *: automatically clones an existing quiz and connect it to the participant'svideo after it gets published.", verbose_name='clone quiz'),
        ),
        migrations.AddField(
            model_name='section',
            name='clone_quiz_reference',
            field=models.ForeignKey(blank=True, help_text="* FOR UPLOAD SECTION ONLY *: quiz that will be cloned and connected to the participant's video afterit gets published.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clone_quiz_reference', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='section',
            name='create_discussions',
            field=models.BooleanField(default=False, help_text="* FOR UPLOAD SECTION ONLY *: automatically create a discussion board based on participant's video submissions.", verbose_name='create discussion'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_output',
            field=models.ForeignKey(blank=True, help_text='* FOR UPLOAD SECTION ONLY *: define the section in which to create the discussion boards.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections_output', to='courses.section', verbose_name='section output'),
        ),
    ]
