# Generated by Django 3.1.13 on 2021-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_auto_20210716_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='access_restriction',
            field=models.CharField(choices=[('P', 'Public'), ('I', 'Instructors'), ('A', 'Admins')], default='P', help_text='Define who should have access to this item.', max_length=1, verbose_name='access restriction'),
        ),
    ]
