# Generated by Django 3.1.13 on 2021-07-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_sectionitem_access_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='clone_quiz',
            field=models.BooleanField(default=False, help_text="* FOR UPLOAD SECTION ONLY *: automatically clones an existing quiz and connect it to the participant's video after it gets published.", verbose_name='clone quiz'),
        ),
    ]
