# Generated by Django 3.1.13 on 2021-07-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_auto_20210723_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='provide_certificate',
            field=models.BooleanField(default=False, help_text='Defines if this course provides a certificate of conclusion.', verbose_name='provide certificate'),
        ),
    ]
