# Generated by Django 3.1.13 on 2021-07-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_auto_20210729_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='requirement'),
        ),
    ]
