# Generated by Django 3.1.13 on 2021-07-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_course_requirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
