# Generated by Django 3.1.13 on 2021-07-30 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0059_course_show_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='editors',
            field=models.ManyToManyField(help_text="List of editors. These users will be able to edit the course's content and structure.", related_name='editor', to=settings.AUTH_USER_MODEL, verbose_name='editors'),
        ),
        migrations.AddField(
            model_name='section',
            name='access_restriction',
            field=models.CharField(choices=[('P', 'Public'), ('L', 'Learners'), ('I', 'Instructors'), ('E', 'Editors'), ('A', 'Admins')], default='P', help_text='Define who should have access to this item.', max_length=1, verbose_name='access restriction'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(help_text='List of instructors. These users will be able to review learners submissions and interact with them.', related_name='instructor', to=settings.AUTH_USER_MODEL, verbose_name='instructors'),
        ),
        migrations.AlterField(
            model_name='section',
            name='published',
            field=models.BooleanField(default=False, help_text="Published items are visible to all users (based on the 'access restriction' parameter). Unpublished items are visible only to editors and admins.", verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='access_restriction',
            field=models.CharField(choices=[('P', 'Public'), ('L', 'Learners'), ('I', 'Instructors'), ('E', 'Editors'), ('A', 'Admins')], default='P', help_text='Define who should have access to this item.', max_length=1, verbose_name='access restriction'),
        ),
    ]
