# Generated by Django 3.1.13 on 2021-09-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_auto_20210903_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='clone_quiz_output_section',
            field=models.ForeignKey(blank=True, help_text='* FOR UPLOAD SECTION ONLY *: define the section which the cloned quiz will be related to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clone_quiz_section', to='courses.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='clone_quiz_update_owner',
            field=models.BooleanField(default=False, help_text='* FOR UPLOAD SECTION ONLY *: updates quiz ownership to uploader', verbose_name='update cloned quiz owner'),
        ),
    ]
