# Generated by Django 3.2.7 on 2021-09-29 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0063_auto_20210904_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='author_access_override',
            field=models.BooleanField(default=False, help_text='Define if author should have access to this item, regardless of the access restriction.', verbose_name='access override for author'),
        ),
        migrations.AddField(
            model_name='section',
            name='output_access_restriction',
            field=models.CharField(choices=[('P', 'Public'), ('L', 'Learners'), ('I', 'Instructors'), ('E', 'Editors'), ('A', 'Admins')], default='P', help_text='* FOR UPLOAD SECTION ONLY *: define who should have access to the new discussion board.', max_length=1, verbose_name='access restriction'),
        ),
        migrations.AddField(
            model_name='section',
            name='output_author_access_override',
            field=models.BooleanField(default=False, help_text='* FOR UPLOAD SECTION ONLY *: define if author should have access, regardless of the access restriction.', verbose_name='access override for author'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='author_access_override',
            field=models.BooleanField(default=False, help_text='Define if author should have access to this item, regardless of the access restriction.', verbose_name='access override for author'),
        ),
    ]
