# Generated by Django 3.2.7 on 2021-10-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_auto_20210929_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='group_by_video',
            field=models.BooleanField(default=False, help_text='* FOR QUIZ ONLY *: group quizzes by videos.', verbose_name='group by video'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_related_video_name',
            field=models.BooleanField(default=False, help_text="* FOR QUIZ ONLY *: enables displaying related video's name.", verbose_name='show related video name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='output_access_restriction',
            field=models.CharField(choices=[('P', 'Public'), ('L', 'Learners'), ('I', 'Instructors'), ('E', 'Editors'), ('A', 'Admins')], default='P', help_text='* FOR UPLOAD SECTION ONLY *: define who should have access to the new discussion board.', max_length=1, verbose_name='output access restriction'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
    ]
