# Generated by Django 3.2.7 on 2021-11-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_auto_20211020_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('C', 'Course'), ('M', 'Module')], default='C', help_text='Sets how the course will be called (for aesthetics purpose only, does not affect functionalities).', max_length=1, verbose_name='course type'),
        ),
    ]
