# Generated by Django 3.2.7 on 2021-12-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_section_paginate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_custom_term',
            field=models.CharField(blank=True, help_text='Certificate custom term.', max_length=150, verbose_name='certificate custom term'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_type',
            field=models.CharField(choices=[('CC', 'Certificate - Course'), ('CX', 'Certificate - Custom')], default='CC', help_text='Defines if the certificate provided will be for the current course or use a customized title.', max_length=2, verbose_name='certificate type'),
        ),
    ]
