# Generated by Django 3.2.7 on 2021-12-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_section_completion_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='completion_message_en',
            field=models.CharField(blank=True, help_text='A message to be displayed after the participant has successfully completed the section. (max 200 characters ', max_length=200, null=True, verbose_name='completion message'),
        ),
        migrations.AddField(
            model_name='section',
            name='completion_message_fr',
            field=models.CharField(blank=True, help_text='A message to be displayed after the participant has successfully completed the section. (max 200 characters ', max_length=200, null=True, verbose_name='completion message'),
        ),
    ]
