# Generated by Django 3.2.7 on 2021-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0071_auto_20211205_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='completion_message',
            field=models.CharField(blank=True, help_text='A message to be displayed after the participant has successfully completed the section. (max 200 characters)', max_length=200, verbose_name='completion message'),
        ),
        migrations.AlterField(
            model_name='section',
            name='completion_message_en',
            field=models.CharField(blank=True, help_text='A message to be displayed after the participant has successfully completed the section. (max 200 characters)', max_length=200, null=True, verbose_name='completion message'),
        ),
        migrations.AlterField(
            model_name='section',
            name='completion_message_fr',
            field=models.CharField(blank=True, help_text='A message to be displayed after the participant has successfully completed the section. (max 200 characters)', max_length=200, null=True, verbose_name='completion message'),
        ),
    ]
