# Generated by Django 3.2.12 on 2022-03-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220330_1955'),
        ('courses', '0072_auto_20211205_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ForeignKey(blank=True, help_text='Certificate template to be used (logos and frame). If no template is defined, certificate will still be created, but on a basic white canvas.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.certificatetemplate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_custom_term',
            field=models.CharField(blank=True, help_text='Certificate custom term to be used instead of the course/module name.', max_length=150, verbose_name='certificate custom term'),
        ),
    ]
