# Generated by Django 3.2.12 on 2022-03-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0073_auto_20220330_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='initial_section_name',
            field=models.CharField(default='Information', help_text='Name for the initial section of the course/module, that shows the description, start/end date, etc.', max_length=25, verbose_name='initial section name'),
        ),
        migrations.AddField(
            model_name='course',
            name='initial_section_name_en',
            field=models.CharField(default='Information', help_text='Name for the initial section of the course/module, that shows the description, start/end date, etc.', max_length=25, null=True, verbose_name='initial section name'),
        ),
        migrations.AddField(
            model_name='course',
            name='initial_section_name_fr',
            field=models.CharField(default='Information', help_text='Name for the initial section of the course/module, that shows the description, start/end date, etc.', max_length=25, null=True, verbose_name='initial section name'),
        ),
    ]
