# Generated by Django 3.2.12 on 2022-03-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0074_auto_20220330_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='auto_enroll',
            field=models.BooleanField(default=False, help_text='Defines if new users should automatically be enrolled to this course/module.', verbose_name='auto enroll'),
        ),
    ]
