# Generated by Django 3.2.13 on 2022-04-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0075_course_auto_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='item_type',
            field=models.CharField(choices=[('CON', 'Content'), ('IMG', 'Image'), ('DIS', 'Discussion'), ('GAM', 'Game'), ('QUZ', 'Quiz'), ('VID', 'Video'), ('PDF', 'PDF')], default='CON', max_length=3, verbose_name='section item type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_items', to='courses.section', verbose_name='section'),
        ),
    ]
