# Generated by Django 3.2.13 on 2022-04-28 15:08

import tinymce.models

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0077_auto_20220415_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionitem",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Item description. Please try to keep it brief (under 1000 characters or 150 words). Only the first 250 characters will be shown in the quiz section view.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="sectionitem",
            name="description_en",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Item description. Please try to keep it brief (under 1000 characters or 150 words). Only the first 250 characters will be shown in the quiz section view.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="sectionitem",
            name="description_fr",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Item description. Please try to keep it brief (under 1000 characters or 150 words). Only the first 250 characters will be shown in the quiz section view.",
                null=True,
                verbose_name="description",
            ),
        ),
    ]
