# Generated by Django 3.2.13 on 2022-04-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0078_auto_20220428_1508"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="content",
        ),
    ]
