# Generated by Django 4.0.4 on 2022-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0081_auto_20220428_1736"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["custom_order"],
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="custom_order",
            field=models.PositiveIntegerField(default=0, verbose_name="custom order"),
        ),
    ]
