# Generated by Django 4.0.4 on 2022-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0082_alter_course_options_course_custom_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("CON", "Content"),
                    ("IMG", "Image"),
                    ("DIS", "Discussion"),
                    ("GAM", "Game"),
                    ("QUZ", "Quiz"),
                    ("VID", "Video"),
                    ("PDF", "PDF"),
                    ("ZIP", "Zip file"),
                ],
                max_length=3,
                verbose_name="section item type",
            ),
        ),
    ]
