# Generated by Django 4.0.4 on 2022-06-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0083_alter_sectionitem_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("CON", "Content"),
                    ("IMG", "Image"),
                    ("DIS", "Discussion"),
                    ("GAM", "Game"),
                    ("QUZ", "Quiz"),
                    ("VID", "Video"),
                    ("PDF", "PDF"),
                    ("ZIP", "Zip file"),
                    ("SCO", "SCORM"),
                ],
                max_length=3,
                verbose_name="section item type",
            ),
        ),
    ]
