# Generated by Django 4.0.7 on 2022-09-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0085_alter_section_section_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                help_text="Section name (max 40 characters)",
                max_length=40,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name_en",
            field=models.CharField(
                help_text="Section name (max 40 characters)",
                max_length=40,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name_fr",
            field=models.CharField(
                help_text="Section name (max 40 characters)",
                max_length=40,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
