# Generated by Django 4.0.8 on 2022-12-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0086_alter_section_name_alter_section_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="show_mark_as_complete_instruction",
            field=models.BooleanField(
                default=True,
                help_text="*FOR CONTENT ONLY *: show the instructions message to mark section as completed. If disabled, only the 'mark as completed' button will be rendered.",
                verbose_name="show instructions to mark section as completed",
            ),
        ),
    ]
