# Generated by Django 4.0.10 on 2023-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0088_section_items_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="show_mark_as_complete_instruction",
            field=models.BooleanField(
                default=False,
                help_text="*FOR CONTENT ONLY *: show the instructions message to mark section as completed. If disabled, only the 'mark as completed' button will be rendered.",
                verbose_name="show instructions to mark section as completed",
            ),
        ),
    ]
