# Generated by Django 4.0.10 on 2023-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0089_alter_section_show_mark_as_complete_instruction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("CD", "Certificate - Default"),
                    ("CX", "Certificate - Custom"),
                ],
                default="CD",
                help_text="Defines if the certificate provided will be for the current course or use a customized term.",
                max_length=2,
                verbose_name="certificate type",
            ),
        ),
    ]
