# Generated by Django 4.0.10 on 2023-04-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0089_alter_section_show_mark_as_complete_instruction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="completion_message",
            new_name="custom_completion_message",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="completion_message_en",
            new_name="custom_completion_message_en",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="completion_message_fr",
            new_name="custom_completion_message_fr",
        ),
    ]
