# Generated by Django 4.0.10 on 2023-04-11 14:32

import model_utils.fields
import tinymce.models

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_helpfaq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0090_alter_course_certificate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Group name (max 150 characters).",
                        max_length=150,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Group name (max 150 characters).",
                        max_length=150,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        help_text="Group name (max 150 characters).",
                        max_length=150,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique group code (max 10 characters)",
                        max_length=10,
                        unique=True,
                        verbose_name="group code",
                    ),
                ),
                (
                    "show_code",
                    models.BooleanField(
                        default=False,
                        help_text="Show group code to instructors.",
                        verbose_name="show group code",
                    ),
                ),
                (
                    "description",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Course description. Please try to keep it brief (under 2000 characters).",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Course description. Please try to keep it brief (under 2000 characters).",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_fr",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Course description. Please try to keep it brief (under 2000 characters).",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "provide_certificate",
                    models.BooleanField(
                        default=False,
                        help_text="Defines if this group provides a certificate of completion.",
                        verbose_name="provide certificate",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("CD", "Certificate - Default"),
                            ("CX", "Certificate - Custom"),
                        ],
                        default="CD",
                        help_text="Defines if the certificate provided will used the name of the group or a customized term.",
                        max_length=2,
                        verbose_name="certificate type",
                    ),
                ),
                (
                    "certificate_custom_term",
                    models.CharField(
                        blank=True,
                        help_text="Certificate custom term to be used instead of the group name.",
                        max_length=150,
                        verbose_name="certificate custom term",
                    ),
                ),
                (
                    "custom_order",
                    models.PositiveIntegerField(default=0, verbose_name="custom order"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "certificate_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Certificate template to be used (logos and frame). If no template is defined, certificate will still be created, but on a basic white canvas.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.certificatetemplate",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="courses.group",
                        verbose_name="requirement",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "ordering": ["custom_order"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Defines which group the course/module will be part of.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.group",
            ),
        ),
    ]
