# Generated by Django 4.0.10 on 2023-04-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0091_group_course_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Defines which group the course/module will be part of.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="courses.group",
            ),
        ),
    ]
