# Generated by Django 4.2.9 on 2024-01-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0092_alter_section_custom_completion_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='mute_audio',
            field=models.BooleanField(default=False, help_text="* FOR UPLOAD SECTION: set audio volume to 'mute', but can be manually adjusted by the user.", verbose_name='mute audio'),
        ),
    ]
