# Generated by Django 3.0.7 on 2020-06-15 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200615_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0004_auto_20200610_1732'),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'discussion', 'verbose_name_plural': 'discussions'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.Discussion', verbose_name='discussion'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=400, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussions', to='courses.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='discussions.Discussion', verbose_name='requirement'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='videos.VideoFile', verbose_name='video'),
        ),
    ]
