# Generated by Django 4.0.7 on 2022-09-05 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_alter_videofile_subtitle_alter_videofile_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0085_alter_section_section_type'),
        ('discussions', '0004_auto_20200615_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDiscussion',
            fields=[
                ('sectionitem_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='courses.sectionitem')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', tinymce.models.HTMLField(blank=True, help_text='Item description. Please try to keep it brief (under 1000 characters or 150 words). Only the first 250 characters will be shown in the quiz section view.', null=True, verbose_name='description')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('access_restriction', models.CharField(choices=[('P', 'Public'), ('L', 'Learners'), ('I', 'Instructors'), ('E', 'Editors'), ('A', 'Admins')], default='P', help_text='Define who should have access to this item.', max_length=1, verbose_name='access restriction')),
                ('author_access_override', models.BooleanField(default=False, help_text='Define if author should have access to this item, regardless of the access restriction.', verbose_name='access override for author')),
                ('show_related_content', models.BooleanField(default=False, help_text='Display content related to this item (e.g., quizzes related to a video)', verbose_name='show related content')),
                ('custom_order', models.PositiveIntegerField(default=0, verbose_name='custom order')),
                ('item_type', models.CharField(choices=[('CON', 'Content'), ('IMG', 'Image'), ('DIS', 'Discussion'), ('GAM', 'Game'), ('QUZ', 'Quiz'), ('VID', 'Video'), ('PDF', 'PDF'), ('ZIP', 'Zip file'), ('SCO', 'SCORM')], max_length=3, verbose_name='section item type')),
                ('last_updated', models.DateTimeField(blank=True, editable=False, verbose_name='last updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.course', verbose_name='course')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='discussions.discussion', verbose_name='requirement')),
                ('section', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.section', verbose_name='section')),
                ('video', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='videos.videofile', verbose_name='video')),
            ],
            options={
                'verbose_name': 'historical discussion',
                'verbose_name_plural': 'historical discussions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
