# Generated by Django 4.0.8 on 2023-02-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0004_auto_20200615_2148"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discussion",
            options={
                "ordering": ["custom_order"],
                "verbose_name": "discussion",
                "verbose_name_plural": "discussions",
            },
        ),
    ]
