# Generated by Django 3.1.12 on 2021-07-06 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/logos/', verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateLogoFile',
            fields=[
                ('logofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.logofile')),
                ('custom_order', models.PositiveIntegerField(default=0, verbose_name='custom order')),
            ],
            options={
                'verbose_name': 'certificate logo file',
                'verbose_name_plural': 'certificate logos files',
                'ordering': ['custom_order'],
            },
            bases=('core.logofile',),
        ),
        migrations.CreateModel(
            name='FooterLogoFile',
            fields=[
                ('logofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.logofile')),
                ('description', models.CharField(help_text='Brief description of the logo (max 255 characters)', max_length=255, verbose_name='description')),
                ('url', models.URLField(help_text='URL of the destination site when the user clicks on the logo.', max_length=255)),
                ('custom_order', models.PositiveIntegerField(default=0, verbose_name='custom order')),
            ],
            options={
                'verbose_name': 'footer logo file',
                'verbose_name_plural': 'footer logos files',
                'ordering': ['custom_order'],
            },
            bases=('core.logofile',),
        ),
    ]
