# Generated by Django 3.2.12 on 2022-03-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateFrameFile',
            fields=[
                ('logofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.logofile')),
            ],
            options={
                'verbose_name': 'certificate frame file',
                'verbose_name_plural': 'certificate frame files',
            },
            bases=('core.logofile',),
        ),
        migrations.AlterModelOptions(
            name='certificatelogofile',
            options={'verbose_name': 'certificate logo file', 'verbose_name_plural': 'certificate logos files'},
        ),
        migrations.RemoveField(
            model_name='certificatelogofile',
            name='custom_order',
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('frame', models.ForeignKey(blank=True, help_text='Image to be displayed as the certificate frame/border (page size: Letter).', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.certificateframefile')),
                ('logos', models.ManyToManyField(blank=True, help_text='Logos to be displayed in the header portion of the certificate. Recommended size is 200x80 points.', to='core.CertificateLogoFile')),
            ],
        ),
    ]
