# Generated by Django 4.0.6 on 2022-07-16 23:36

import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20220415_1556"),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name="certificatetemplate",
            name="logos",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text="Logos to be displayed in the header portion of the certificate. Recommended size is 200x80 points.",
                to="core.certificatelogofile",
            ),
        ),
    ]
