# Generated by Django 4.0.6 on 2022-07-26 15:45

import model_utils.fields
import tinymce.models

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_certificatetemplate_logos"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpFaq",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="Question for the Help FAQ (max 255 characters)",
                        max_length=255,
                        verbose_name="question",
                    ),
                ),
                (
                    "question_en",
                    models.CharField(
                        help_text="Question for the Help FAQ (max 255 characters)",
                        max_length=255,
                        null=True,
                        verbose_name="question",
                    ),
                ),
                (
                    "question_fr",
                    models.CharField(
                        help_text="Question for the Help FAQ (max 255 characters)",
                        max_length=255,
                        null=True,
                        verbose_name="question",
                    ),
                ),
                (
                    "answer",
                    tinymce.models.HTMLField(
                        help_text="Answer for the Help FAQ question."
                    ),
                ),
                (
                    "answer_en",
                    tinymce.models.HTMLField(
                        help_text="Answer for the Help FAQ question.", null=True
                    ),
                ),
                (
                    "answer_fr",
                    tinymce.models.HTMLField(
                        help_text="Answer for the Help FAQ question.", null=True
                    ),
                ),
                (
                    "custom_order",
                    models.PositiveIntegerField(default=0, verbose_name="custom order"),
                ),
            ],
            options={
                "ordering": ["custom_order"],
            },
        ),
    ]
