# Generated by Django 3.0.7 on 2020-06-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20200615_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
