# Generated by Django 3.2.7 on 2021-12-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dashboard name (max 150 characters).', max_length=150, unique=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, help_text="'Hero' image that will be displayed on top portion of the dashboard (home page).", null=True, upload_to='uploads/dashboard/', verbose_name='image')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
    ]
