# Generated by Django 3.2.7 on 2021-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='active',
            field=models.BooleanField(verbose_name='active'),
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='unique_active_dashboard'),
        ),
    ]
