# Generated by Django 3.2.7 on 2021-12-03 22:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211203_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='instructions_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='instructions_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='name_en',
            field=models.CharField(help_text='Dashboard name (max 150 characters).', max_length=150, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='name_fr',
            field=models.CharField(help_text='Dashboard name (max 150 characters).', max_length=150, null=True, unique=True, verbose_name='name'),
        ),
    ]
