# Generated by Django 3.2.7 on 2021-12-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211203_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard',
            new_name='DashboardSettings',
        ),
    ]
