# Generated by Django 4.0.4 on 2022-06-02 21:44

import core.support_methods
import upload_validator

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0084_alter_sectionitem_item_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScormObject",
            fields=[
                (
                    "sectionitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="courses.sectionitem",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Format accepted: zip.",
                        upload_to=core.support_methods.user_directory_path_not_random,
                        validators=[
                            upload_validator.FileTypeValidator(
                                allowed_types=["application/zip"]
                            )
                        ],
                        verbose_name="SCORM package",
                    ),
                ),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("courses.sectionitem",),
        ),
    ]
