# Generated by Django 4.0.4 on 2022-06-04 20:45

import model_utils.fields

import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0002_remove_scormobject_url_scormobject_package_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scormregistration",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="scormregistration",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
