# Generated by Django 4.0.4 on 2022-06-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0085_alter_section_section_type"),
        ("scorm", "0003_scormregistration_created_scormregistration_modified"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ScormObject",
            new_name="ScormPackage",
        ),
    ]
