# Generated by Django 4.0.4 on 2022-06-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0004_rename_scormobject_scormpackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="scormregistration",
            name="activity_completion",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="scormregistration",
            name="activity_success",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="scormregistration",
            name="attempts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scormregistration",
            name="completion_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scormregistration",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scormregistration",
            name="time_tracked",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
