# Generated by Django 4.0.4 on 2022-06-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0005_scormregistration_activity_completion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scormregistration",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
